import { mkdir, readFile, readdir, unlink, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";
import process from "node:process";

const ROOT = resolve(new URL("..", import.meta.url).pathname);
const SITE_URL = "https://jerwis.fr";
const TODAY = "2026-05-22";
const DATA_PATH = join(ROOT, "data", "lexique.json");
const HUB_PATH = join(ROOT, "lexique.html");
const SITEMAP_PATH = join(ROOT, "sitemap.xml");
const OUT_DIR = join(ROOT, "lexique");
const HUB_START = "<!-- LEXIQUE_AZ_GENERATED_START -->";
const HUB_END = "<!-- LEXIQUE_AZ_GENERATED_END -->";
const SITEMAP_START = "  <!-- Lexique SEO pages · generated by scripts/build-lexique.js -->";
const SITEMAP_END = "  <!-- /Lexique SEO pages -->";
const GENERATED_MARKER = "<!-- generated:lexique-term -->";

const PRIORITY_MAP = {
  P1: "0.72",
  P2: "0.64",
  P3: "0.58",
};

function escapeHtml(value = "") {
  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function escapeAttr(value = "") {
  return escapeHtml(value).replace(/`/g, "&#96;");
}

function slugFirstLetter(title) {
  return title
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .trim()
    .charAt(0)
    .toUpperCase();
}

function publicUrl(term) {
  return term.page ? `${SITE_URL}/lexique/${term.slug}` : `${SITE_URL}/lexique#${term.slug}`;
}

function localHref(term) {
  return term.page ? `lexique/${term.slug}.html` : `#${term.slug}`;
}

function compactDescription(term) {
  const raw = `${term.summary} Exemple concret, erreurs fréquentes et mots liés.`;
  if (raw.length <= 145) return raw;
  const truncated = raw.slice(0, 142);
  return `${truncated.slice(0, truncated.lastIndexOf(" "))}...`;
}

function normalizeSearch(term) {
  return [term.title, term.category, term.summary, term.where, ...(term.aliases || [])]
    .join(" ")
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/&/g, " et ")
    .replace(/[./_-]+/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function validate(data) {
  const errors = [];
  const slugs = new Set();
  const slugPattern = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;
  if (!Array.isArray(data.terms)) errors.push("data.terms doit être un tableau.");

  for (const term of data.terms || []) {
    if (!term.slug || !slugPattern.test(term.slug)) errors.push(`Slug invalide: ${term.slug}`);
    if (slugs.has(term.slug)) errors.push(`Slug dupliqué: ${term.slug}`);
    slugs.add(term.slug);
    for (const key of ["title", "category", "summary", "where"]) {
      if (!term[key]) errors.push(`${term.slug}: champ manquant ${key}`);
    }
    if (term.page) {
      for (const key of ["intent", "angle", "example", "why"]) {
        if (!term[key]) errors.push(`${term.slug}: champ SEO manquant ${key}`);
      }
      if (!Array.isArray(term.mistakes) || term.mistakes.length < 3) {
        errors.push(`${term.slug}: au moins 3 erreurs fréquentes attendues`);
      }
      if (!Array.isArray(term.related) || term.related.length < 3) {
        errors.push(`${term.slug}: au moins 3 termes liés attendus`);
      }
    }
  }

  for (const term of data.terms || []) {
    for (const related of term.related || []) {
      if (!slugs.has(related)) errors.push(`${term.slug}: related introuvable ${related}`);
    }
  }

  if (errors.length) {
    throw new Error(errors.map((error) => `- ${error}`).join("\n"));
  }
}

function groupByLetter(terms) {
  return terms
    .toSorted((a, b) => a.title.localeCompare(b.title, "fr", { sensitivity: "base" }))
    .reduce((groups, term) => {
      const letter = slugFirstLetter(term.title);
      if (!groups.has(letter)) groups.set(letter, []);
      groups.get(letter).push(term);
      return groups;
    }, new Map());
}

function renderAzList(terms) {
  const groups = groupByLetter(terms);
  const blocks = Array.from(groups.entries()).map(([letter, termsForLetter]) => {
    const rows = termsForLetter.map((term) => {
      const badge = term.page ? "Page détaillée" : "Définition express";
      const href = localHref(term);
      const groupsAttr = ["all", ...(term.page ? ["pages"] : []), ...(term.groups || [])].join(" ");
      return `          <li class="lex-az-term" data-term-id="${escapeAttr(term.slug)}" data-term-letter="${escapeAttr(letter)}" data-term-groups="${escapeAttr(groupsAttr)}" data-term-search="${escapeAttr(normalizeSearch(term))}">
            <a href="${escapeAttr(href)}">
              <span>
                <strong>${escapeHtml(term.title)}</strong>
                <small>${escapeHtml(term.summary)}</small>
              </span>
              <em>${escapeHtml(badge)}</em>
            </a>
          </li>`;
    }).join("\n");
    return `      <section class="lex-letter-group" data-lex-az-group="${escapeAttr(letter)}" aria-labelledby="lex-letter-${escapeAttr(letter.toLowerCase())}">
        <h3 id="lex-letter-${escapeAttr(letter.toLowerCase())}">${escapeHtml(letter)}</h3>
        <ul class="lex-term-list">
${rows}
        </ul>
      </section>`;
  }).join("\n");

  return `${HUB_START}
      <div class="lex-az-list" id="lexAzList" aria-label="Liste alphabétique complète du lexique">
${blocks}
      </div>
${HUB_END}`;
}

function renderDefinedTermSet(data) {
  const hasDefinedTerm = data.terms.map((term) => ({
    "@type": "DefinedTerm",
    "name": term.title,
    "url": publicUrl(term),
    "description": term.summary,
    "inDefinedTermSet": `${SITE_URL}/lexique#termset`,
  }));

  const schema = {
    "@context": "https://schema.org",
    "@type": "DefinedTermSet",
    "@id": `${SITE_URL}/lexique#termset`,
    "name": "Lexique IA pour non-devs",
    "description": "70 mots IA, agents et outils expliqués en français simple, avec recherche, index A-Z, filtres et pages détaillées pour les notions clés.",
    "inLanguage": "fr-FR",
    "url": `${SITE_URL}/lexique`,
    "author": {
      "@type": "Person",
      "name": "Jérémy Sagnier",
      "url": `${SITE_URL}/`,
    },
    hasDefinedTerm,
  };

  return `<!-- Schema.org : DefinedTermSet (glossaire) -->
<script type="application/ld+json">
${JSON.stringify(schema, null, 2)}
</script>`;
}

function renderRelatedLink(current, related) {
  const href = related.page ? `./${related.slug}.html` : `../lexique.html#${related.slug}`;
  return `<a href="${escapeAttr(href)}">${escapeHtml(related.title)}</a>`;
}

function renderTermPage(term, allTerms) {
  const related = (term.related || [])
    .map((slug) => allTerms.find((candidate) => candidate.slug === slug))
    .filter(Boolean);
  const relatedLinks = related.map((item) => renderRelatedLink(term, item)).join("");
  const compareLinks = related.slice(0, 2);
  const canonical = `${SITE_URL}/lexique/${term.slug}`;
  const title = `${term.title} : définition IA simple · Lexique Jerwis`;
  const description = compactDescription(term);
  const faq = [
    {
      q: `C'est quoi ${term.title} en IA ?`,
      a: term.summary,
    },
    {
      q: `Où vais-je croiser ${term.title} ?`,
      a: term.where,
    },
    {
      q: `Quel mot lire après ${term.title} ?`,
      a: related.length ? `Commence par ${related.slice(0, 3).map((item) => item.title).join(", ")}.` : "Reviens au glossaire A-Z pour continuer.",
    },
  ];
  const definedTerm = {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "BreadcrumbList",
        "itemListElement": [
          { "@type": "ListItem", "position": 1, "name": "Accueil", "item": `${SITE_URL}/` },
          { "@type": "ListItem", "position": 2, "name": "Lexique IA", "item": `${SITE_URL}/lexique` },
          { "@type": "ListItem", "position": 3, "name": term.title, "item": canonical },
        ],
      },
      {
        "@type": "WebPage",
        "@id": `${canonical}#webpage`,
        "url": canonical,
        "name": title,
        "description": description,
        "inLanguage": "fr-FR",
        "isPartOf": { "@id": `${SITE_URL}/lexique#termset` },
        "mainEntity": { "@id": `${canonical}#term` },
      },
      {
        "@type": "DefinedTerm",
        "@id": `${canonical}#term`,
        "name": term.title,
        "description": term.summary,
        "url": canonical,
        "inDefinedTermSet": `${SITE_URL}/lexique#termset`,
      },
    ],
  };

  return `<!DOCTYPE html>
<html lang="fr" data-theme="light">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${escapeHtml(title)}</title>
<meta name="description" content="${escapeAttr(description)}">
<meta property="og:title" content="${escapeAttr(title)}">
<meta property="og:description" content="${escapeAttr(description)}">
<meta property="og:url" content="${escapeAttr(canonical)}">
<meta property="og:type" content="article">
<meta property="og:locale" content="fr_FR">
<meta property="og:image" content="${SITE_URL}/photos/og-jerwis.jpg">
<meta property="og:image:height" content="630">
<meta property="og:image:width" content="1200">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="@JeremySagnier">
<meta name="twitter:creator" content="@JeremySagnier">
<meta name="twitter:title" content="${escapeAttr(title)}">
<meta name="twitter:description" content="${escapeAttr(description)}">
<meta name="twitter:image" content="${SITE_URL}/photos/og-jerwis.jpg">
<link rel="canonical" href="${escapeAttr(canonical)}">
<link rel="icon" href="../favicon.svg" type="image/svg+xml">
<link rel="icon" href="../favicon.ico" sizes="any">
<link rel="apple-touch-icon" href="../apple-touch-icon.png">
<link rel="manifest" href="../site.webmanifest">
<meta name="theme-color" content="#0A0A0A">
<link rel="stylesheet" href="../assets/fonts.css">
<link rel="stylesheet" href="../assets/lexique-pages.css">
<script type="application/ld+json">
${JSON.stringify(definedTerm, null, 2)}
</script>
</head>
<body>
${GENERATED_MARKER}
<div class="triple-stripe" aria-hidden="true"><span style="background:#00B2A9"></span><span style="background:#EF426F"></span><span style="background:#FF8200"></span></div>
<header class="term-header">
  <a class="term-logo" href="../index.html"><span></span>Jerwis</a>
  <nav aria-label="Navigation">
    <a href="../apprendre.html">Apprendre</a>
    <a href="../lexique.html">Lexique IA</a>
    <a href="../index.html#newsletters">Newsletters</a>
  </nav>
</header>

<main>
  <section class="term-hero">
    <div class="term-container">
      <a class="term-back" href="../lexique.html">← Retour au glossaire A-Z</a>
      <div class="term-kicker">Glossaire IA · ${escapeHtml(term.priority || "Définition")}</div>
      <h1>${escapeHtml(term.title)}</h1>
      <p class="term-lead">${escapeHtml(term.summary)}</p>
      <div class="term-meta">
        <span>${escapeHtml(term.category)}</span>
        <span>Lecture 4 min</span>
        <span>Mis à jour le ${TODAY}</span>
      </div>
    </div>
  </section>

  <div class="mini-marquee" aria-hidden="true">
    <div class="mini-marquee-track">
      <span>Définition simple</span><span>Exemple concret</span><span>Erreurs fréquentes</span><span>Mots liés</span><span>Retour au glossaire</span>
      <span>Définition simple</span><span>Exemple concret</span><span>Erreurs fréquentes</span><span>Mots liés</span><span>Retour au glossaire</span>
    </div>
  </div>

  <section class="term-definition">
    <div class="term-container">
      <span class="section-kicker">— Définition</span>
      <h2>${escapeHtml(term.title)}, en clair</h2>
      <p>${escapeHtml(term.summary)}</p>
      <p>${escapeHtml(term.angle)}</p>
    </div>
  </section>

  <div class="term-container term-layout">
    <article class="term-content">
      <section>
        <h2>Exemple concret</h2>
        <p>${escapeHtml(term.example)}</p>
      </section>

      <section>
        <h2>Pourquoi ça compte</h2>
        <p>${escapeHtml(term.why)}</p>
        <p>${escapeHtml(term.where)}</p>
      </section>

      <section>
        <h2>À ne pas confondre</h2>
        ${compareLinks.map((item) => `<p><strong>${escapeHtml(item.title)}</strong> : ${escapeHtml(item.summary)}</p>`).join("\n        ")}
      </section>

      <section>
        <h2>Erreurs fréquentes</h2>
        <ul>
          ${(term.mistakes || []).map((mistake) => `<li>${escapeHtml(mistake)}</li>`).join("\n          ")}
        </ul>
      </section>

      <section>
        <h2>Mini-checklist</h2>
        <ul>
          <li>Je vérifie d'abord si le mot désigne un concept, un outil, un risque ou une métrique.</li>
          <li>Je le relie à un cas concret : ${escapeHtml(term.example)}</li>
          <li>Je garde en tête le piège principal : ${escapeHtml((term.mistakes || [])[0] || "ne pas utiliser le mot hors contexte.")}</li>
        </ul>
      </section>

      <section class="term-faq">
        <h2>Questions rapides</h2>
        ${faq.map((item) => `<details><summary>${escapeHtml(item.q)}</summary><p>${escapeHtml(item.a)}</p></details>`).join("\n        ")}
      </section>
    </article>

    <aside class="term-side" aria-label="Navigation liée">
      <div class="term-side-card">
        <h2>Mots liés</h2>
        <div class="term-related-links">
          ${relatedLinks}
        </div>
      </div>
      <div class="term-side-card">
        <h2>Dans le glossaire</h2>
        <p>La version courte reste dans la liste A-Z, avec les autres mots du même univers.</p>
        <a class="term-side-cta" href="../lexique.html#${escapeAttr(term.slug)}">Voir dans le hub</a>
      </div>
    </aside>
  </div>

  <div class="mini-marquee" aria-hidden="true">
    <div class="mini-marquee-track">
      <span>Comprendre sans jargon</span><span>Relier les mots</span><span>Garder les sources</span><span>Tester doucement</span><span>Réponds si tu vois une erreur</span>
      <span>Comprendre sans jargon</span><span>Relier les mots</span><span>Garder les sources</span><span>Tester doucement</span><span>Réponds si tu vois une erreur</span>
    </div>
  </div>

  <section class="term-final">
    <div class="term-container">
      <h2>Tu veux continuer dans l'ordre ?</h2>
      <p>Reviens au glossaire complet, cherche un mot, puis ouvre seulement les pages qui méritent plus qu'une définition courte.</p>
      <a href="../lexique.html">Ouvrir le glossaire IA</a>
    </div>
  </section>
</main>

<footer class="term-footer">
  <p>© 2026 · Jérémy Sagnier · Jerwis</p>
</footer>
</body>
</html>
`;
}

async function updateHub(data) {
  let html = await readFile(HUB_PATH, "utf8");
  const az = renderAzList(data.terms);
  if (!html.includes(HUB_START) || !html.includes(HUB_END)) {
    throw new Error(`Markers ${HUB_START} / ${HUB_END} absents de lexique.html`);
  }
  html = html.replace(new RegExp(`${HUB_START}[\\s\\S]*?${HUB_END}`), az);
  html = html.replace(
    /<!-- Schema\.org : DefinedTermSet \(glossaire\) -->\n<script type="application\/ld\+json">[\s\S]*?<\/script>/,
    renderDefinedTermSet(data),
  );
  await writeFile(HUB_PATH, html);
}

async function cleanupGeneratedPages() {
  await mkdir(OUT_DIR, { recursive: true });
  const files = await readdir(OUT_DIR).catch(() => []);
  await Promise.all(files.map(async (file) => {
    if (!file.endsWith(".html")) return;
    const fullPath = join(OUT_DIR, file);
    const content = await readFile(fullPath, "utf8");
    if (content.includes(GENERATED_MARKER)) await unlink(fullPath);
  }));
}

async function writeTermPages(data) {
  await cleanupGeneratedPages();
  const pageTerms = data.terms.filter((term) => term.page);
  await Promise.all(pageTerms.map((term) => (
    writeFile(join(OUT_DIR, `${term.slug}.html`), renderTermPage(term, data.terms))
  )));
  return pageTerms;
}

function renderSitemapBlock(pageTerms) {
  const urls = pageTerms
    .toSorted((a, b) => a.title.localeCompare(b.title, "fr", { sensitivity: "base" }))
    .map((term) => `  <url>
    <loc>${SITE_URL}/lexique/${term.slug}</loc>
    <lastmod>${term.lastmod || TODAY}</lastmod>
    <changefreq>monthly</changefreq>
    <priority>${PRIORITY_MAP[term.priority] || "0.55"}</priority>
  </url>`)
    .join("\n\n");
  return `${SITEMAP_START}
${urls}
${SITEMAP_END}`;
}

async function updateSitemap(pageTerms) {
  let sitemap = await readFile(SITEMAP_PATH, "utf8");
  sitemap = sitemap.replace(
    /(<loc>https:\/\/jerwis\.fr\/lexique<\/loc>\s*<lastmod>)([^<]+)(<\/lastmod>)/,
    `$1${TODAY}$3`,
  );
  const block = renderSitemapBlock(pageTerms);
  if (sitemap.includes(SITEMAP_START) && sitemap.includes(SITEMAP_END)) {
    sitemap = sitemap.replace(new RegExp(`${SITEMAP_START}[\\s\\S]*?${SITEMAP_END}`), block);
  } else {
    sitemap = sitemap.replace(/\n\s*<!-- Pages légales -->/, `\n\n${block}\n\n  <!-- Pages légales -->`);
  }
  await writeFile(SITEMAP_PATH, sitemap);
}

async function main() {
  const checkOnly = process.argv.includes("--check");
  const data = JSON.parse(await readFile(DATA_PATH, "utf8"));
  validate(data);
  const pageTerms = data.terms.filter((term) => term.page);

  if (!checkOnly) {
    await updateHub(data);
    await writeTermPages(data);
    await updateSitemap(pageTerms);
  }

  console.log(`Lexique OK · ${data.terms.length} termes · ${pageTerms.length} pages dédiées${checkOnly ? " · check only" : ""}`);
}

main().catch((error) => {
  console.error(error.message);
  process.exit(1);
});
